### ISSUE TITLE
JS source code seems to be missing?

### ISSUE THREAD

**Issue by mhansen** [Xuhpclab/drcctprof-viewer#1]
Hi there, I'm trying to map DrCCTProf and it's inputs and outputs and UIs for https://www.markhansen.co.nz/profilerpedia/. I found this repo, it seems to be a VSCode extension, but most of the source seems missing? It only seems to have 'res' files. I'd like to see the source to find out what profile formats are supported -- I heard maybe pprof and perf, but I can't find perf in the README.

Thanks!

**Comment by mhansen** [comment]
Also, is the image in this blogpost the same as the VSCode extension or is it something different? https://xl10.github.io/blog/drcctprof.html

**Comment by xl10** [comment]
Hello. The blog you pointed out is the profiling tool DrCCTProf. This extension is designed for a more generic purpose to visualize more data format beyond just DrCCTProf. We support pprof format. We also support the output format for any tools that support hatchet format.

**Comment by mhansen** [comment]
Thanks. Is it intentional that this repo only has a `res` folder and no javascript code? I expected to see some JS code implementing the extension?

**Comment by xl10** [comment]
We haven't released the code yet. This is a book-keeping repository.

**Comment by mhansen** [comment]
Thanks. Is the DrCCTProf GUI shown in the blog available? I couldn’t find
reference to a DrCCTProf GUI in the docs or readme:

**Comment by xl10** [comment]
The GUI in the blog is Hpcviewer (the GUI for HPCToolkit). DrCCTProf can output the HPCToolkit format for Hpcviewer.

**Comment by mhansen** [comment]
Ah, thanks. That gives me the information i think i need to connect these
up. Have a good one! 👋

**Comment by mhansen** [comment]
One more favour, could you confirm I have this right?

https://profilerpedia.markhansen.co.nz/profilers/drcctprof/
https://profilerpedia.markhansen.co.nz/uis/drcctprof-viewer/

![image](https://user-images.githubusercontent.com/105529/139389753-fd590868-1471-4086-803e-ddee7899d39b.png)

Thank you!

**Comment by xl10** [comment]
Yes. That’s correct. Thank you.
